# docker-compose.yml
  # Use root/example as user/password credentials
version: '3.6'

services:
  mongo:
    image: mongo
    container_name: db_mongo
    restart: always
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: supersafe
      MONGO_INITDB_DATABASE: cookie

    ports:
      - "27017:27017"